export const Members = [
    {
      title: "Sallin Koutev",
      img: "Sallin.webp",
      linkedin: "https://www.linkedin.com/in/sallin-koutev-216b0016b/",
      lastPosition: "",
    },
    {
      title: "Caitlin Syho",
      img: "Caitlin.webp",
      linkedin: "https://www.linkedin.com/in/caitlinsyho/",
      lastPosition: "",
    },
    {
      title: "Kian Hoseinkhani",
      img: "Kian.webp",
      linkedin: "https://www.linkedin.com/in/kian-hosseinkhani-716a311b6/",
      lastPosition: "",
    },
    {
      title: "Karan Pathak",
      img: "blueprint.webp",
      linkedin: "https://www.linkedin.com/in/karanpathak/",
      lastPosition: "",
    },
    {
      title: "Kate Simone",
      img: "Kate.webp",
      linkedin: "https://www.linkedin.com/in/kate-simone-866335284/",
      lastPosition: "",
    },
    {
      title: "Eugene Zhu",
      img: "Eugene.webp",
      linkedin: "https://www.linkedin.com/in/eugenezhu/",
      lastPosition: "",
    },
    {
      title: "Kasey Le",
      img: "blueprint.webp",
      linkedin: "https://www.linkedin.com/in/kasey-le-43aa31255/",
      lastPosition: "",
    },
    {
      title: "Alison Lu",
      img: "Alison.webp",
      linkedin: "https://www.linkedin.com/in/alisonlu3/",
      lastPosition: "",
    },
    {
      title: "Firm Kong Thong",
      img: "Firm.webp",
      linkedin: "https://www.linkedin.com/in/firm-kongthong/",
      lastPosition: "",
    },
    {
      title: "Duc Dang",
      img: "blueprint.webp",
      linkedin: "https://www.linkedin.com/in/ddang2001/",
      lastPosition: "",
    },
    {
      title: "Tomi Lui",
      img: "blueprint.webp",
      linkedin: "https://www.linkedin.com/in/tomi-lui-3955631b3/",
      lastPosition: "",
    },
    {
      title: "Terry Kwok",
      img: "Terry.webp",
      linkedin: "https://www.linkedin.com/in/lai-chit-kwok-6074472b5/",
      lastPosition: "",
    },
    {
      title: "Supriya Dua",
      img: "Supriya.webp",
      linkedin: "https://www.linkedin.com/in/supriya-dua-a8a576204/",
      lastPosition: "",
    },
    {
      title: "Peiman Zhiani",
      img: "Peiman.webp",
      linkedin: "https://www.linkedin.com/in/peiman-zhiani/",
      lastPosition: "",
    },
    {
      title: "Enoch Muwanguzi",
      img: "blueprint.webp",
      linkedin: "https://www.linkedin.com/in/enoch-muwanguzi-42491425b/",
      lastPosition: "",
    },
    {
      title: "Abishek Deshpande",
      img: "blueprint.webp",
      linkedin: "https://www.linkedin.com/in/abhishek-deshpande-a01132179/",
      lastPosition: "",
    },
    {
      title: "Jeffrey Wong",
      img: "blueprint.webp",
      linkedin: "https://www.linkedin.com/in/wong-jeffrey/",
      lastPosition: "",
    },
    {
      title: "Brayden Sue",
      img: "Brayden.webp",
      linkedin: "",
      lastPosition: "",
    },
    
    {
      title: "Gursewak Singh",
      img: "Gursewak.webp",
      linkedin: "https://www.linkedin.com/in/gursewak-singh-310a111a4/",
      lastPosition: "",
    },
    {
      title: "Meghna Rajamohan",
      img: "Meghna.webp",
      linkedin: "http://www.linkedin.com/in/meghna-rajamohan-a787452a7",
      lastPosition: "",
    },
    {
      title: "Samuel Miranda",
      img: "Samuel.webp",
      linkedin: "https://www.linkedin.com/in/samuel-antunes-467a0a214",
      lastPosition: "",
    },
    {
      title: "Hinako Kamiya",
      img: "Hinako.webp",
      linkedin: "https://www.linkedin.com/in/hinako-kamiya/",
      lastPosition: "",
    },
    {
      title: "Vinh Dang",
      img: "Quang.webp",
      linkedin: "https://www.linkedin.com/in/quang-vinh-dang-788ab0194/",
      lastPosition: "",
    },
    {
      title: "Ayana Hussain",
      img: "Ayana.webp",
      linkedin: "https://www.linkedin.com/in/ayana-hussain-a3399a227/",
      lastPosition: "",
    },{
      title: "Amy Zhao",
      img: "Amy.webp",
      linkedin: "https://www.linkedin.com/in/amy-zhao-/",
      lastPosition: "",
    },{
      title: "Johnson Luong",
      img: "Johnson.webp",
      linkedin: "https://www.linkedin.com/in/johnson-luong/",
      lastPosition: "",
    },{
      title: "Derek Huang",
      img: "Derek.webp",
      linkedin: "https://www.linkedin.com/in/derekhuang1/",
      lastPosition: "",
    },{
      title: "Duy Nguyen",
      img: "Duy.webp",
      linkedin: "https://www.linkedin.com/in/duwe-ng/",
      lastPosition: "",
    },{
      title: "Monishka Gautam",
      img: "Monishka.webp",
      linkedin: "https://www.linkedin.com/in/monishka-gautam/",
      lastPosition: "",
    },{
      title: "Zahila Rehman",
      img: "Zahila.webp",
      linkedin: "https://www.linkedin.com/in/zahila-rehman-9118a4217/",
      lastPosition: "",
    },{
      title: "Fabian Siswanto",
      img: "Fabian.webp",
      linkedin: "https://www.linkedin.com/in/fabiansiswanto/",
      lastPosition: "",
    },{
      title: "Mrinal Goshalia",
      img: "Mrinal.webp",
      linkedin: "https://www.linkedin.com/in/mrinal-goshalia/",
      lastPosition: "",
    }, {
      title: "Jai Malhi",
      img: "blueprint.webp",
      linkedin: "https://www.linkedin.com/in/jaimalhi/",
  
    },
];
