export const Members = [
  {
    title: "Caitlin Syho",
    img: "Caitlin.webp",
    linkedin: "https://www.linkedin.com/in/caitlinsyho/",
    lastPosition: "",
  },

  {
    title: "Kate Simone",
    img: "Kate.webp",
    linkedin: "https://www.linkedin.com/in/kate-simone-866335284/",
    lastPosition: "",
  },
  {
    title: "Eugene Zhu",
    img: "Eugene.webp",
    linkedin: "https://www.linkedin.com/in/eugenezhu/",
    lastPosition: "",
  },

  {
    title: "Duc Dang",
    img: "blueprint.webp",
    linkedin: "https://www.linkedin.com/in/ddang2001/",
    lastPosition: "",
  },
  {
    title: "Jeffrey Wong",
    img: "Jeffrey.webp",
    linkedin: "https://www.linkedin.com/in/wong-jeffrey/",
    lastPosition: "",
  },
  {
    title: "Brayden Sue",
    img: "Brayden.webp",
    linkedin: "",
    lastPosition: "",
  },
  {
    title: "Tulika Varma",
    img: "Tulika.webp",
    linkedin: "",
    lastPosition: "",
  },
  {
    title: "Kousha Amouzesh",
    img: "Kousha.webp",
    linkedin: "https://www.linkedin.com/in/kousha-amouzesh/",
    lastPosition: "",
  },
  {
    title: "Iris Au-Yeung",
    img: "blueprint.webp",
    linkedin: "https://www.linkedin.com/in/irisau-yeung/",
    lastPosition: "",
  },

  {
    title: "Gursewak Singh",
    img: "Gursewak.webp",
    linkedin: "https://www.linkedin.com/in/gursewak-singh-310a111a4/",
    lastPosition: "",
  },  
  {
    title: "Meghna Rajamohan",
    img: "Meghna.webp",
    linkedin: "http://www.linkedin.com/in/meghna-rajamohan-a787452a7",
    lastPosition: "",
  },
  {
    title: "Samuel Miranda",
    img: "Samuel.webp",
    linkedin: "https://www.linkedin.com/in/samuel-antunes-467a0a214",
    lastPosition: "",
  },
  {
    title: "Vinh Dang",
    img: "Quang.webp",
    linkedin: "https://www.linkedin.com/in/quang-vinh-dang-788ab0194/",
    lastPosition: "",
  },
  {
    title: "Ayana Hussain",
    img: "Ayana.webp",
    linkedin: "https://www.linkedin.com/in/ayana-hussain-a3399a227/",
    lastPosition: "",
  },
  {
    title: "Amy Zhao",
    img: "Amy.webp",
    linkedin: "https://www.linkedin.com/in/amy-zhao-/",
    lastPosition: "",
  },
  {
    title: "Johnson Luong",
    img: "Johnson.webp",
    linkedin: "https://www.linkedin.com/in/johnson-luong/",
    lastPosition: "",
  },
  {
    title: "Derek Huang",
    img: "Derek.webp",
    linkedin: "https://www.linkedin.com/in/derekhuang1/",
    lastPosition: "",
  },
  {
    title: "Fabian Siswanto",
    img: "Fabian.webp",
    linkedin: "https://www.linkedin.com/in/fabiansiswanto/",
    lastPosition: "",
  },
  {
    title: "Mrinal Goshalia",
    img: "Mrinal.webp",
    linkedin: "https://www.linkedin.com/in/mrinal-goshalia/",
    lastPosition: "",
  },
  {
    title: "Jai Malhi",
    img: "Jai.webp",
    linkedin: "https://www.linkedin.com/in/jaimalhi/",
    lastPosition: "",
  },
  {
    title: "Teddy Malhan",
    img: "Teddy.webp",
    linkedin: "https://www.linkedin.com/in/teddymalhan/",
    lastPosition: "",
  },
  {
    title: "Lauryn Yau",
    img: "blueprint.webp",
    linkedin: "https://www.linkedin.com/in/laurynyau/",
    lastPosition: "",
  },
  {
    title: "Joshua li",
    img: "blueprint.webp",
    linkedin: "https://www.linkedin.com/in/joshuajli/",
    lastPosition: "",
  },
  {
    title: "Jerry Deng",
    img: "blueprint.webp",
    linkedin: "https://www.linkedin.com/in/jerrydngzh/",
    lastPosition: "",
  },
  {
    title: "Jimmy Hui",
    img: "Jimmy.webp",
    linkedin: "https://www.linkedin.com/in/jimmy--hui/",
    lastPosition: "",
  },
  {
    title: "Bryan Dang",
    img: "blueprint.webp",
    linkedin: "https://www.linkedin.com/in/bryanjhdang/",
    lastPosition: "",
  },
  {
    title: "Lauren Yip",
    img: "blueprint.webp",
    linkedin: "https://www.linkedin.com/in/lauren-yip/",
    lastPosition: "",
  },
];
